### ISSUE TITLE
Translation TODO

### ISSUE THREAD

**Issue by Tunguso4ka** [Tunguso4ka/CM-14#5]
### Список файлів/тек що потребують перекладу.

- [ ] Сутності (Resources/Locale/ua-UK/_CM14/entities_locale/)
  - [ ] Зброя та набої (Resources/Locale/ua-UK/_CM14/entities_locale/entities/objects/weapons/guns/)
  - [ ] Вендори (Resources/Locale/ua-UK/_CM14/entities_locale/entities/structures/machines/)
  - [ ] Шафи (Resources/Locale/ua-UK/_CM14/entities_locale/entities/structures/storage)
  - [ ] Постери (Resources/Locale/ua-UK/_CM14/entities_locale/entities/structures/wallmounts/signs)
  - [ ] Барикади (Resources/Locale/ua-UK/_CM14/entities_locale/entities/structures/walls)
  - [ ] Вікна (Resources/Locale/ua-UK/_CM14/entities_locale/entities/structures/windows)

- [ ] Інтерфейсу апстріма (Resources/Locale/ua-UK)

- [ ] Виправлення помилок (переклад ніколи не буває легким, тому якщо ви знайшли помилку: виправте її новим PRом, вкажить на неї через Issues, або повідомте [мене](https://discord.com/users/636156844934430720), дякую <3 )

### Дякую всім хто допомогає проекту.
Ім'я кожного (за вашим бажанням я можу не додавати вас) хто перекладав або редактував переклад попаде в Титри перекладу.

**Comment by Stanislav4ix** [comment]
Беру на себе переклад зброї та набоїв, потім побачимо:)

**Comment by Stanislav4ix** [comment]
Беру на себе шафи

**Comment by Tunguso4ka** [comment]
> Беру на себе шафи

шафи вже на Banfor20min

**Comment by Stanislav4ix** [comment]
Беру вікна

**Comment by Stanislav4ix** [comment]
Беру барикади

**Comment by Stanislav4ix** [comment]
Беру постери

**Comment by Stanislav4ix** [comment]
Беру сповіщення
